<a href="https://colab.research.google.com/github/DaniilDonskoy/building_maintenance_agents/blob/feature%2Fincident-data-analysis/research/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7_%D0%B7%D0%B0%D1%8F%D0%B2%D0%BE%D0%BA_%D0%BC%D0%B0%D1%80%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

In [ ]:
sheet_id = "1ya7OgCwUC3a_BylVxideUUAe5I18Pbr4"
sheet_name = "Sheet1"

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

df = pd.read_csv(url)

print(df.columns)
display(df.head(1))

Index(['Журнал заявок\nООО "Эксплуатация Главстрой-СПб"\nОтчёт сформирован 16.03.2026 09:17 Дата',
       'Время', 'Источник', 'Адрес', 'Пом.', 'Категория', 'Подкатегория',
       'Описание', 'Комментарий к выполненным работам', 'Статус заявки',
       'Желаемое время выполнения', 'Дата исполнения', 'Исполнители',
       'Координаторы', 'Перечень материалов', 'Услуги', 'Стоимость',
       'Вложения'],
      dtype='object')

,"Журнал заявок\nООО ""Эксплуатация Главстрой-СПб""\nОтчёт сформирован 16.03.2026 09:17 Дата",Время,Источник,Адрес,Пом.,Категория,Подкатегория,Описание,Комментарий к выполненным работам,Статус заявки,Желаемое время выполнения,Дата исполнения,Исполнители,Координаторы,Перечень материалов,Услуги,Стоимость,Вложения
0,15.03.2026,23:19,Диспетчер,"г Санкт-Петербург, п Парголово, ул Николая Рубцова, д. 5 стр. 1",309,Аварийная,Протечка,"СИЛЬНАЯ ТЕЧЬ СТОЯКА ГВС В ВАННОЙ, ОТКЛ. СТ. 29 ГВС В/З, ТРЕБ. ЗАМЕНА ОТСЕЧНОГО КРАНА, ВЫРВАЛО ШТОК\nГИЛЬДИЯ: Заменили два крана 1/2 на хгвс ст. 29 в/з\nЗапустили развоздушили",NaN,Принята к исполнению,с 09:00 16.03.2026 по 13:00 16.03.2026,NaN,NaN,"ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Бригадир санитарно-технических работ Журавский Антон Петрович",NaN,NaN,0,Нет

# Предпросмотр

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 18 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Журнал заявок
ООО "Эксплуатация Главстрой-СПб"
Отчёт сформирован 16.03.2026 09:17 Дата  458 non-null    object
 1   Время                                                                                   458 non-null    object
 2   Источник                                                                                458 non-null    object
 3   Адрес                                                                                   458 non-null    object
 4   Пом.                                                                                    176 non-null    object
 5   Категория                                                                               458 non-null    object
 6   Подкатегория                                                                            458 non-null    object
 7   Описание                                                                                458 non-null    object
 8   Комментарий к выполненным работам                                                       0 non-null      float64
 9   Статус заявки                                                                           458 non-null    object
 10  Желаемое время выполнения                                                               446 non-null    object
 11  Дата исполнения                                                                         0 non-null      float64
 12  Исполнители                                                                             0 non-null      float64
 13  Координаторы                                                                            455 non-null    object
 14  Перечень материалов                                                                     0 non-null      float64
 15  Услуги                                                                                  0 non-null      float64
 16  Стоимость                                                                               458 non-null    int64
 17  Вложения                                                                                458 non-null    object
dtypes: float64(5), int64(1), object(12)
memory usage: 726.1 KB

In [ ]:
display(df['Пом.'].value_counts())
display(df['Пом.'].unique()) #Пом. - это квартира? и что означают буквы в номере

Пом.
267     3
450     3
141     3
26      2
237     2
       ..
1064    1
680     1
708     1
739     1
611     1
Name: count, Length: 157, dtype: int64

array(['309', '267', '575', nan, '21', '1', '742', '555', '90', '168',
       '129', '856', '252', '540', '919', '566', '26', '6', '1116', '672',
       '41', '1206', '451', '218', '807', '270', '930', '237', '94',
       '786', '201', '2063', '1037П', '83Н', '524', '1160', '199', '110Н',
       '584', '513', '428', '2495', '95', '32', '128', '216', '145',
       '1274', '946', '519', '313', '491', '404', '18', '75', '956',
       '507', '504', '146', '835', '351', '559', '1024П', '531', '74',
       '335', '67', '982', '1050', '968', '593', '89', '736', '311',
       '64Н', '1129', '279', '482', '1311', '410', '1Н', '264', '379',
       '187', '717', '204', '126', '1658', '562', '29Н', '396', '395',
       '572', '50', '450', '2', '510', '31', '864', '453', '630', '1378',
       '81', '1221', '1047', '178', '1143', '421', '38', '220', '662',
       '141', '97', '312', '44Н', '1310', '678', '29', '28Н', '535',
       '160Н', '175', '71', '2944', '87', '212', '1019П', '25', '1350',
       '117', '354', '908', '155', '1347', '136', '275', '972', '35Н',
       '140', '980', '525', '370', '322', '247', '1638', '24', '213',
       '2984', '9Н', '2129П', '65Н', '36', '1054', '1064', '680', '708',
       '739', '611'], dtype=object)

In [ ]:
df['Источник'].value_counts() # житель = из обращения?

Источник
Диспетчер       415
Житель           35
Из обращения      8
Name: count, dtype: int64

In [ ]:
df['Категория'].value_counts() #бесполезный признак

Категория
Аварийная    458
Name: count, dtype: int64

In [ ]:
df['Подкатегория'].value_counts()

Подкатегория
Лифт                214
Протечка            193
Электроснабжение     49
Прочие работы         2
Name: count, dtype: int64

In [ ]:
df[df['Подкатегория'] == 'Прочие работы']

# ТЕЧЬ РАДИАТОРА В КОМНАТЕ попала в 'Прочие работы' -> тип заявки лучше узнавать из описания

,"Журнал заявок\nООО ""Эксплуатация Главстрой-СПб""\nОтчёт сформирован 16.03.2026 09:17 Дата",Время,Источник,Адрес,Пом.,Категория,Подкатегория,Описание,Комментарий к выполненным работам,Статус заявки,Желаемое время выполнения,Дата исполнения,Исполнители,Координаторы,Перечень материалов,Услуги,Стоимость,Вложения
195,09.03.2026,11:18,Диспетчер,"г Санкт-Петербург, п Парголово, ул Михаила Дудина, д. 25 корп. 1 лит. А",64Н,Аварийная,Прочие работы,"КП, СТУДИЯ КРАСОТЫ ""ЛАЗЕР ПРО ЛАБ""- ВЫТЕКАНИЕ ИЗ УНИТАЗА 89811614344\nГИЛЬДИЯ6Промыли лежак канализации в подвале кипятком 12 метров. требуется убрать воду в подвале с 5 парадной по 4ю",NaN,Принята к исполнению,с 10:00 10.03.2026 по 12:00 10.03.2026,NaN,NaN,ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА,NaN,NaN,0,Нет
298,05.03.2026,17:37,Диспетчер,"г Санкт-Петербург, п Парголово, ул Михаила Дудина, д. 25 корп. 2 лит. А",1143,Аварийная,Прочие работы,ТЕЧЬ РАДИАТОРА В КОМНАТЕ 89312870024\n20:26 Пребрали соединение батареи радиатора,NaN,Принята к исполнению,с 17:45 05.03.2026 по 18:00 05.03.2026,NaN,NaN,"ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович",NaN,NaN,0,Нет

In [ ]:
df['Комментарий к выполненным работам'].isna().sum()

np.int64(458)

In [ ]:
df['Статус заявки'].value_counts()

Статус заявки
Принята к исполнению    458
Name: count, dtype: int64

In [ ]:
df['Дата исполнения'].isna().sum() #мб полезный признак, узнаем время на работу

np.int64(458)

In [ ]:
df['Исполнители'].isna().sum() # полезно, чтобы узнать количество задействованных людей

np.int64(458)

In [ ]:
df['Координаторы'].value_counts() #заполнено, но непонятно как использовать

Координаторы
Спецтрест 27 – ЛИФТ Шкапцов А Л, Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                           91
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА                                                                                                                                                                                                                     84
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович, Спецтрест 27 – ЛИФТ Шкапцов А Л                                                           62
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович                                                                                                                                                                           54
Главный инженер Софронов Андрей Иванович                                                                                                                                                                                                                    47
Спецтрест 27 – ЛИФТ Шкапцов А Л                                                                                                                                                                                                                             24
Главный инженер Софронов Андрей Иванович, ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА                                                                                                                                                                           23
Спецтрест 27 – ЛИФТ Шкапцов А Л, Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович                                                                                                                                        11
Спецтрест 27 Шкапцов А Л, Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                                   6
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                                                             6
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Бригадир санитарно-технических работ Дайнаков Юрий Игоревич                                                                                                                                                         4
Главный инженер Софронов Андрей Иванович, ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Бригадир санитарно-технических работ Дайнаков Юрий Игоревич                                                                                                               4
Начальник отделения Григорьев Игорь Валерьевич                                                                                                                                                                                                               4
Ведущий инженер Длатовский Кирилл Андреевич                                                                                                                                                                                                                  3
Спецтрест 27 – ЛИФТ Шкапцов А Л, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович, Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович                                                            2
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович, Главный энергетик Михайлов Олег Владимирович                                                                                                                              2
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович, Бригадир санитарно-технических работ Дайнаков Юрий Игоревич                                                                                                               2
Спецтрест 27 – ЛИФТ Шкапцов А Л, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                                                                                                                 2
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович, Администратор Частина Любовь Владимировна, Бригадир санитарно-технических работ Катаев Вадим Валерьевич                                                                   1
Начальник отделения Григорьев Игорь Валерьевич, Начальник отдела Пиляцкас Виталюс Альгердо                                                                                                                                                                   1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Бригадир санитарно-технических работ Журавский Антон Петрович                                                                                                                                                       1
Бригадир ремонтно-строительных работ Григорович Анатолий Михайлович                                                                                                                                                                                          1
Ведущий инженер Исаев Илгам Наби Оглы                                                                                                                                                                                                                        1
Администратор Сенченко Елена Валерьевна, Администратор Яровая Евгения Павловна                                                                                                                                                                               1
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович, Ведущий инженер Бавыкин Андрей Викторович, Начальник отделения Мидеева Наида Вагидовна     1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Администратор Яровая Евгения Павловна, Администратор Сенченко Елена Валерьевна                                                                                                                                      1
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Спецтрест 27 – ЛИФТ Шкапцов А Л, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                            1
Мастер по эксплуатации и ремонту Гафиятуллин Рамиль Равилевич                                                                                                                                                                                                1
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович, Спецтрест 27 Шкапцов А Л, Спецтрест 27 – ЛИФТ Шкапцов А Л                                  1
Администратор Сенченко Елена Валерьевна, Администратор Яровая Евгения Павловна, Главный инженер Софронов Андрей Иванович                                                                                                                                     1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович                                                    1
Спецтрест 27 – ЛИФТ Шкапцов А Л, Главный инженер Софронов Андрей Иванович                                                                                                                                                                                    1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Ведущий инженер Исаев Илгам Наби Оглы                                                                                                                                                                               1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Бригадир ремонтно-строительных работ Григорович Анатолий Михайлович                                                                                                                                                 1
Ведущий инженер по подъемно-транспортному оборудованию Гореликов Павел Вячеславович, Инженер по подъемно-транспортному оборудованию Горюнов Сергей Александрович, Спецтрест 27 – ЛИФТ Шкапцов А Л, Администратор Новикова Ирина Александровна                1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Администратор Давыскиба Меланья Петровна                                                                                                                                                                            1
Администратор Яровая Евгения Павловна                                                                                                                                                                                                                        1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Главный инженер Софронов Андрей Иванович, Ведущий инженер Бавыкин Андрей Викторович                                                                                                                                 1
Главный инженер Софронов Андрей Иванович, Начальник службы Филатова Маргарита Алексеевна                                                                                                                                                                     1
ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Администратор Сенченко Елена Валерьевна, Администратор Яровая Евгения Павловна                                                                                                                                      1
Главный инженер Софронов Андрей Иванович, ГИЛЬДИЯ СЕРВИСА ГИЛЬДИЯ СЕРВИСА СЕРВИСА, Начальник отдела Поляков Алексей Николаевич                                                                                                                               1
Бригадир санитарно-технических работ Лисицын Алексей Анатольевич                                                                                                                                                                                             1
Name: count, dtype: int64

In [ ]:
df['Перечень материалов'].isna().sum()

np.int64(458)

In [ ]:
df['Услуги'].isna().sum()

np.int64(458)

In [ ]:
df['Стоимость'].value_counts()

Стоимость
0    458
Name: count, dtype: int64

In [ ]:
df['Вложения'].value_counts() # Что здесь имеется в виду? что означает да/нет?

Вложения
Нет    434
Да      24
Name: count, dtype: int64

# Статистика по инцидентам